### ISSUE TITLE
Convert any ASS subtitle.. not working, does not show up in plugin flow

### ISSUE THREAD

**Issue by jhockert** [Unmanic/unmanic-plugins#153]
Converting ASS subtitles to SRT doesnt seem to be working. It does not show up in plugin flow setting

Unmanic Version:
0.1.4~655b18b
Python Version:
3.8.10.final.0
Running on unraid

found this error

> 2021-12-19T22:17:04:ERROR:Unmanic.PluginExecutor - [FORMATTED] - Exception encountered while importing module 'convert_subtitle_streams_ass_to_srt' - No module named 'normalise_aac'
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 160, in __load_plugin_module
> 
>     module_spec.loader.exec_module(plugin_import)
> 
>   File "", line 848, in exec_module
> 
>   File "", line 219, in _call_with_frames_removed
> 
>   File "/config/.unmanic/plugins/convert_subtitle_streams_ass_to_srt/plugin.py", line 29, in 
> 
>     from normalise_aac.lib.ffmpeg import StreamMapper, Probe, Parser
> 
> ModuleNotFoundError: No module named 'normalise_aac'

**Comment by jhockert** [comment]
When installing and enabling "Normalise AAC Audio Streams" it does work, seems that this plugin cant be used standalone and is dependent of "Normalise AAC Audio Streams"
