### ISSUE TITLE
Encoder / Remux failing when there's no codec_type

### ISSUE THREAD

**Issue by takkorai** [Unmanic/unmanic-plugins#226]
Logging the issue flagged on discord.
Although Unmanic works great when it works, it's not working many of my files are getting skipped/failing. 
Below is the exception/error that remux and encoders spit out.

```
2022-03-08T23:47:30:ERROR:Unmanic.PluginExecutor - [FORMATTED] - Exception while carrying out 'worker.process_item' plugin runner 'video_remuxer'

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 272, in execute_plugin_runner

    runner(data)

  File "/config/.unmanic/plugins/video_remuxer/plugin.py", line 262, in on_worker_process

    mapper.streams_need_processing()

  File "/config/.unmanic/plugins/video_remuxer/lib/ffmpeg/stream_mapper.py", line 319, in streams_need_processing

    return self.__set_stream_mapping()

  File "/config/.unmanic/plugins/video_remuxer/lib/ffmpeg/stream_mapper.py", line 183, in __set_stream_mapping

    if stream_info.get('codec_type').lower() == "video":

AttributeError: 'NoneType' object has no attribute 'lower'

```

```
2022-03-08T23:47:31:ERROR:Unmanic.PluginExecutor - [FORMATTED] - Exception while carrying out 'worker.process_item' plugin runner 'video_remuxer'

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 272, in execute_plugin_runner

    runner(data)

  File "/config/.unmanic/plugins/video_remuxer/plugin.py", line 262, in on_worker_process

    mapper.streams_need_processing()

  File "/config/.unmanic/plugins/video_remuxer/lib/ffmpeg/stream_mapper.py", line 319, in streams_need_processing

    return self.__set_stream_mapping()

  File "/config/.unmanic/plugins/video_remuxer/lib/ffmpeg/stream_mapper.py", line 183, in __set_stream_mapping

    if stream_info.get('codec_type').lower() == "video":

AttributeError: 'NoneType' object has no attribute 'lower'

```

**Comment by Josh5** [comment]
Resolved. Please update the plugins ad retry
